---
title: " "
# author: "IntellSci Research Organization"
# date: "2/21/2021"
#runtime: shiny

output:
  github_document:
  #slidy_presentation:
 # ioslides_presentation:
  #  theme: darkly
 #   toc: true
 #    toc_float: true 
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# All about the Website

**[SERVICES](#services) for SOCIAL AND COMMERCIAL PURPOSES**
- **[TARGETED THOUGHT-ENERGY THERAPY](#TTT)**


**PROGRAMS ON [SELF-INTELLIGENCE](#selfintelligence)**

+ **[BEING YOU](#beingyou)**

+ [BEYOND SCHOOL](#beyondschool)

+ [SKILL INTELLIGENCE](#skillintelligence)
   # - [Daily Data Science Bootcamp](#DDS)
   # - [Internship Projects](#internship)
    - Daily Data Science Bootcamp
    - Internship Projects

+ [SCIENTIFIC INTELLIGENCE](#scientificintelligence)

  + Artificial Intelligence for All - AIFA
  + Artificial Intelligence for Mathematicians
  + Mathematics for Social Sciences
  + Engineering Analytics
  + General Psychology for Developers
  + Data Psychology for Developers
  + Analytical Programming for All
  + Automatic Programming for All
  + Actuarial Sciences


+ [DIVINE INTELLIGENCE](#divine_intelligence)



