---
#title: "Self-intelligence Programs"
# author: "Hazel"
# date: "2/22/2021"

output:
  html_document:
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###	{.tabset .tabset-fade .tabset-pills}

#### ->

#### "BEYOND SCHOOL" 

  - Skill Intelligence
  - Divine Intelligence
  -	Scientific Intelligence
  
  - Social Life Skills
  -	Self-Grooming Skills    
  
  -	Aspiration (Role/Goal based) Videos 
  - Motivation (Intention based) Videos 
  - Educative and Informative Videos
  
  - Goal Designing
  - Career Mapping
  - Purpose Definition
  - Capability Enhancement
  - Assessments: 
      - Intelligence, Learning Style, Personality, Need Analysis 
  - Routine Checks: 
      - Sleep, Diet, Physical Activity, Emotional Energy, Moral Behaviour


#### "BEING YOU" 

    - Content based on Ancient Scriptures on Philosophy of Life
    
    - TARGETED THOUGHT-ENERGY THERAPY
    
    - Self-assess, Self-heal, Self-rejuvenate, Self-aware Assessments
    
    - Mind and Thought Cleansing
    
    - Routine Checks
    
    - Thought Pattern Analysis
    
  - Engage your individual lunar power
    
  - Identify the triggers of your hormonal imbalance
    
  - Learn the right lesson from your pain (physical and emotional)
    
  - Heal the root of your dis-comfort or dis-ease
  
  - Rectify the triggers of your dis-comfort
  
  - Prevent the physical manifestation of your hereditary complaints
  
  - Realize your individual emotional balance
  
  - Match the YAMAS and NIYAMAS in your living
  
  - Raise your inner vibrational frequency and vital energy
  
  - Match your career goal with your true personality and intelligence
  
  - Study your Thought Energy Pattern
  
  - Resolve your hidden trauma and fear
  
  - Break your barriers of abuse

#### SKILL INTELLIGENCE {.tabset}

##### Daily Data Science Boot Camp

      -	Related to an aspect of daily life
      -	Projects to address real life requirements
      -	Obtain optimal, practical, beneficial solutions
      -	Customized and self-paced hands-on project experience
      -	Individual/Group-based projects/case studies/research
      -	Completely involving Project management  
      -	Individualized Capability Enhancement
      -	Bottom-up approach of role assignment
      -	Commercialization of project results
      -	No bar on age, gender, qualification, role 
  
##### Internship Projects

    - Goal Designing
    - Career Mapping
    - Purpose Definition
    - Capability Enhancement:
      - Focus and Concentration
      - Intention and Manifestation
      - Ideation and Execution
      - Conceptualization and Implementation
      - Empathy and Generosity
      - Patience and Humility 

    -	Projects to address real life requirements
    -	Obtain optimal, practical, beneficial solutions
    -	Customized and self-paced hands-on project experience
    -	Individual/Group-based projects/case studies/research
    -	Completely involving Project management  
    -	Commercialization of project results
    -	No bar on age, gender, qualification, role 


####	SCIENTIFIC INTELLIGENCE
  
  Artificial Intelligence for All (AIFA)
  
  Artificial Intelligence for Mathematicians
    
  Mathematics for Social Sciences
  
  Engineering Analytics
    
  General Psychology for Developers
  
  Data Psychology for Developers

  Analytical Programming for All
  
  Automatic Programming for All
    
  Actuarial Sciences
    
####	Divine Intelligence
  - Book
  - YouTube videos
  - Podcast
  - Live Chat
   

    
